name: Checkout Example

on : [push]

jobs:
  checkout-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List the files
        run: ls -la
